{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "render-worker.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "render-worker.labels" . | nindent 4 }}
data:
  {{- if .Values.configMap.data }}
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ printf "%v" $value | quote }}
  {{- end }}
  {{- else }}
  RENDER_PROFILE: "default"
  {{- end }}
{{- end }}
