{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "render-worker.fullname" . }}-sqs
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "render-worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "render-worker.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  triggers:
    - type: {{ include "render-worker.kedaTriggerType" . }}
      metadata:
        queueURLFromEnv: {{ include "render-worker.kedaQueueURLFromEnv" . | quote }}
        queueLength: {{ include "render-worker.kedaQueueLength" . | quote }}
        awsRegion: {{ include "render-worker.kedaAWSRegion" . | quote }}
      {{- if .Values.keda.authentication.enabled }}
      authenticationRef:
        name: {{ default (printf "%s-sqs-auth" (include "render-worker.fullname" .)) .Values.keda.authentication.name }}
      {{- end }}
{{- end }}
